# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.ibm.com_operandrequests.yaml
- bases/operator.ibm.com_operandconfigs.yaml
- bases/operator.ibm.com_operandbindinfos.yaml
- bases/operator.ibm.com_operandregistries.yaml
- bases/operator.ibm.com_namespacescopes.yaml


