apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: operand-deployment-lifecycle-manager
    app.kubernetes.io/managed-by: operand-deployment-lifecycle-manager
    app.kubernetes.io/name: operand-deployment-lifecycle-manager
  name: operandconfigs.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: OperandConfig
    listKind: OperandConfigList
    plural: operandconfigs
    shortNames:
    - opcon
    singular: operandconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Current Phase
      jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Created At
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: OperandConfig is the Schema for the operandconfigs API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OperandConfigSpec defines the desired state of OperandConfig.
            properties:
              services:
                description: Services is a list of configuration of service.
                items:
                  description: ConfigService defines the configuration of the service.
                  properties:
                    name:
                      description: Name is the subscription name.
                      type: string
                    resources:
                      description: Resources is used to specify the kubernetes resources
                        that are needed for the service.
                      items:
                        description: ConfigResource defines the resource needed for
                          the service
                        properties:
                          annotations:
                            additionalProperties:
                              type: string
                            description: Annotations are the annotations used in the
                              resource.
                            type: object
                          apiVersion:
                            description: APIVersion defines the versioned schema of
                              this representation of an object.
                            type: string
                          data:
                            description: Data is the configuration map of kubernetes
                              resource.
                            nullable: true
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          force:
                            default: true
                            description: Force is used to determine whether the existing
                              kubernetes resource should be overwritten.
                            type: boolean
                          kind:
                            description: Kind identifies the kind of the kubernetes
                              resource.
                            type: string
                          labels:
                            additionalProperties:
                              type: string
                            description: Labels are the labels used in the resource.
                            type: object
                          name:
                            description: Name is the resource name.
                            type: string
                          namespace:
                            description: Namespace is the namespace of the resource.
                            type: string
                        required:
                        - apiVersion
                        - kind
                        - name
                        type: object
                      type: array
                    spec:
                      additionalProperties:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      description: Spec is the configuration map of custom resource.
                      type: object
                    state:
                      description: State is a flag to enable or disable service.
                      type: string
                  required:
                  - name
                  type: object
                type: array
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: OperandConfigStatus defines the observed state of OperandConfig.
            properties:
              phase:
                description: Phase describes the overall phase of operands in the
                  OperandConfig.
                type: string
              serviceStatus:
                additionalProperties:
                  description: CrStatus defines the status of the custom resource.
                  properties:
                    customResourceStatus:
                      additionalProperties:
                        description: ServicePhase defines the service status.
                        type: string
                      type: object
                  type: object
                description: ServiceStatus defines all the status of a operator.
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
