kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: meta-operator
subjects:
- kind: ServiceAccount
  name: meta-operator
  namespace: ibm-common-services
roleRef:
  kind: ClusterRole
  name: meta-operator
  apiGroup: rbac.authorization.k8s.io
